### ISSUE TITLE
[third-party] update Coinlib 

### ISSUE THREAD

**Issue by maiuei** [myceworld/myce#23]
https://coinlib.io/coin/YCE/Myce

**Comment by maiuei** [comment]
Send and email with all the information for the update.

**Comment by maiuei** [comment]
no response, just send another email again.

**Comment by bitcoinsfacil** [comment]
update @maiuei ?

**Comment by maiuei** [comment]
no response, send 2 email's and fill up a request on website

**Comment by bitcoinsfacil** [comment]
update @maiuei ?

**Comment by maiuei** [comment]
no response from them!
